### ISSUE TITLE
fatal error: 'linux/joystick.h' file not found

### ISSUE THREAD

**Issue by ryandesign** [psemiletov/tea-qt#19]
Hello,

TEA 45.0.0 fails to build on macOS 10.12.6 with this error:

```
In file included from rvln.cpp:73:
In file included from ./rvln.h:52:
In file included from ./document.h:52:
./myjoystick.h:14:10: fatal error: 'linux/joystick.h' file not found
#include <linux/joystick.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [rvln.o] Error 1
```

**Comment by psemiletov** [comment]
Thank you!
Now it is fixed (I hope), as I've added some ifdefs to the code to check MacOS.

**Comment by ryandesign** [comment]
Thanks. It looks like it's actually supposed to be `Q_OS_MAC` not `Q_OS_MACOS`. If I make that change, it builds.

**Comment by daniloegea** [comment]
Hello.

You should use Q_OS_LINUX where you use the Joystick feature. I am the maintainer of the FreeBSD's port of tea and the new version is not building (same problem) :(

**Comment by psemiletov** [comment]
Thanks for the report, fixed!

**Comment by daniloegea** [comment]
Fixed on FreeBSD. Thanks! ;)

**Comment by psemiletov** [comment]
Thank you for cooperation :)
