### ISSUE TITLE
unknown type name 'CJoystickAxisEvent'

### ISSUE THREAD

**Issue by yurikoles** [psemiletov/tea-qt#21]
While building 45.0.2 on macOS
```
In file included from main.cpp:25:
In file included from ./rvln.h:52:
./document.h:345:31: error: unknown type name 'CJoystickAxisEvent'
  void handle_joystick_event (CJoystickAxisEvent *ev);
```
[Full log](https://gist.github.com/5bab4cfb0f89611c0d0205936be6abc1)

**Comment by yurikoles** [comment]
This issue seems to be fixed master.

**Comment by yurikoles** [comment]
Please issue a new release.

**Comment by psemiletov** [comment]
https://github.com/psemiletov/tea-qt/releases/tag/45.0.2 has been already released with this fix

**Comment by yurikoles** [comment]
seems to be caused by #24

**Comment by yurikoles** [comment]
@vasilewvv ty debil?

**Comment by psemiletov** [comment]
Прямо LOR какой-то.
